version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: md5
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - data-postgres:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - data-mongo:/data/db

  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /
      AMQP_URL: amqp://rabbitmq?connection_attempts=5&retry_delay=5
    volumes:
      - data-rabbitmq:/var/lib/rabbitmq

volumes:
  data-postgres:
    name: data-postgres
    driver: local
  data-mongo:
    name: data-mongo
    driver: local
  data-rabbitmq:
    name: data-rabbitmq
    driver: local